### ISSUE TITLE
Task 1

### ISSUE THREAD

**Issue by alordev** [tomncooper/CSC8101-Documentation#1]
I am trying to do Task 1 and I had two ideas how to approach it:
1. For each row in the netflix dataset search the whole canonical dataset matching for the title and then output the ID of the netflix row and the canonical title. This is O(n^2) and even though I could sort the canonical ds by date and use binary search I don't know how to do this in Python and also in Spark.
2. Use a hashmap and put films released in the same year with the same key in the hashmap and their titles in a list as a value to this key. This would be O(n). I managed to form a list of tuples, and using groupByKey seems to return more or less the correct representation.

I noticed however the RDD can be iterated neither with a for loop nor within a lambda statement ('PipelinedRDD object is not iterable') and so it seems like the pair RDDs could be the solution (I am mostly looking at groupByKey and combineByKey methods).
Is my assumption correct that we should only rely on RDDs rather than on using Python collections?
Could you give a hint on which direction should I aim for?

**Comment by tomncooper** [comment]
You should try to use RDD based operations wherever possible. You should take advantage of pair RDDs, in Python these are formed from tuples in the form (key, value). Once you have keys you can perform **join** operations to link two pair RDDs. If you reorganise your canonical titles and Netflix titles so that they have common keys you can join them together efficently without needing to resort to local maps or iterators. 

So I would look at the RDD.join() documentation (there are several different types of join) and figure out how you can reorganise the two RDDs so that they have common keys.
