### ISSUE TITLE
Sparkstreaming sparkcontext error

### ISSUE THREAD

**Issue by jwang727** [tomncooper/CSC8101-Documentation#23]
I can't seem to get the sparkcontext defined. I am using the stub file as a base and I get 

'ValueError: Cannot run multiple SparkContexts at once; existing SparkContext(app=streamcode.py, master=local[*]) created by getOrCreate at /home/ubuntu/sparkstreaming/streamcode.py:30 '

at line

'SC = SparkContext(master="local[2]", appName="Event Processing", conf=sp_conf)'.

If I run SC.stop() just before defining SC, I get 'NameError: name 'sc' is not defined' instead.

I am pretty sure the problem isn't caused by the sparkcontext I used for the batch coursework either since I ran sc.stop() on that already.

Also is there any way to run the code on a notebook rather than using $ spark-submit --packages com.datastax.spark:spark-cassandra-connector_2.11:2.0.0-M3,org.apache.spark:spark-streaming-kafka-0-8_2.11:2.1.0 your_streaming_program.py?  Because on the notebook the code seem to be able to pass the 'SC = SparkContext(master="local[2]", appName="Event Processing", conf=sp_conf)'. line but I get the following error instead:

Spark Streaming's Kafka libraries not found in class path. Try one of the following.

  1. Include the Kafka library and its dependencies with in the
     spark-submit command as

     $ bin/spark-submit --packages org.apache.spark:spark-streaming-kafka-0-8:2.1.0 ...

  2. Download the JAR of the artifact from Maven Central http://search.maven.org/,
     Group Id = org.apache.spark, Artifact Id = spark-streaming-kafka-0-8-assembly, Version = 2.1.0.
     Then, include the jar in the spark-submit command as

     $ bin/spark-submit --jars <spark-streaming-kafka-0-8-assembly.jar> ...

________________________________________________________________________________________________

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-4253c7909cab> in <module>()
     89                                        "BrokerIP:34.249.15.212",
     90                                        150487641,
---> 91                                        {"dev-streaming": 1})
     92 
     93 ########## Window the incoming batches ##########

/home/ubuntu/spark/spark-2.1.0-bin-hadoop2.7/python/pyspark/streaming/kafka.py in createStream(ssc, zkQuorum, groupId, topics, kafkaParams, storageLevel, keyDecoder, valueDecoder)
     67             raise TypeError("topics should be dict")
     68         jlevel = ssc._sc._getJavaStorageLevel(storageLevel)
---> 69         helper = KafkaUtils._get_helper(ssc._sc)
     70         jstream = helper.createStream(ssc._jssc, kafkaParams, topics, jlevel)
     71         ser = PairDeserializer(NoOpSerializer(), NoOpSerializer())

/home/ubuntu/spark/spark-2.1.0-bin-hadoop2.7/python/pyspark/streaming/kafka.py in _get_helper(sc)
    193     def _get_helper(sc):
    194         try:
--> 195             return sc._jvm.org.apache.spark.streaming.kafka.KafkaUtilsPythonHelper()
    196         except TypeError as e:
    197             if str(e) == "'JavaPackage' object is not callable":

TypeError: 'JavaPackage' object is not callable

**Comment by tomncooper** [comment]
As per the instructions in the coursework documentation, Juypter notebooks are not recommended for developing streaming jobs due to the continuous running nature of spark streaming programs.

Did you try to open the stub file in a notebook? If so this would be the source of your first error as the notebook already has a spark context and the stub file is trying to create a second one. 

You should load the stub file as a .py file onto your VM and open it in a command line editor like `nano`. You should edit the relevant sections as per the documentation and run it using the `spark-submit` program.

**Comment by jwang727** [comment]
So even if I just opened the .py file on Jupyter (so not even a notebook file) I'll get the error because Jupyter automatically sets up the SparkContext?

**Comment by tomncooper** [comment]
Yes, the notebook server on your VM is set up to use `pyspark` as its Python interpreter so will create a SparkContext object (`sc`) by default every time you start it up. 

If you really want to use a notebook then you can simply comment out the SparkContext creation line in the stub file (it is there because `spark-submit` does not create one by default) and run if from there using the `sc` created by the notebook server. However, if you go down this route bare in mind that we will not help you with any notebook related issues as we have already warned you about the difficulties of using notebooks with spark streaming.

**Comment by jwang727** [comment]
I copied the file to another different folder (created on terminal) and I am now running the .py file on the command line yet I still get the same error?

ValueError: Cannot run multiple SparkContexts at once; existing SparkContext(app=streamingcode.py, master=local[*]) created by getOrCreate at /home/ubuntu/sparkstreamingtry1/streamingcode.py:25

**Comment by tomncooper** [comment]
Is your notebook server still running?

Are you running the unchanged stub-file? 

Are you running it with `spark-submit --packages <kakfa and cassandra packages> stub.py ` ?

**Comment by jwang727** [comment]
I am running an edited version of the stub file which I copy and pasted from Jupyter, saved as a python file on my own computer, and then uploaded to the VM using a scp command.

I am running it with spark-submit --packages <kakfa and cassandra packages> yes.

**Comment by tomncooper** [comment]
Have you looked to see if Jupyter has added any additional code to the top of this file? Is there another SparkContext in your code? 

Have you compared it to the `stub.py` file in the repository to identify any differences that may be causing the issue?

**Comment by jwang727** [comment]
I just ran the original stub.py file (in its original location, instead of a copy of it in another folder) and it seems to let me run without the error, thanks.
