### ISSUE TITLE
Spark batch Task 6 - materialising on the driver?

### ISSUE THREAD

**Issue by sshephard2** [tomncooper/CSC8101-Documentation#5]
In the task 6 hint:

> Hint: It may be easier to bring RDD contents to a session which you create on the driver, rather than attempting to pass sessions to executors via a map function over an RDD. Look up the various methods for materialising RDDs **on the spark driver** and try to pick the most efficient.

I'm finding "driver" slightly ambiguous here - I think this means do something to get the data into your code (Python notebook in my case) then pass that data to the Bolt driver? Rather than materialising the data into the Bolt driver?  In which case I think I know how to do this but I was wondering if we were expected to find a cleverer way?

**Comment by hugofirth** [comment]
Hi @sshephard2 

You are correct. There is an overloading of terms going on here.

* The Neo4j library which contains the code for connecting to a Bolt endpoint and writing to a database is called a **driver**. 
* The process where most of your spark job's code is executed is also called a **driver**.

In that part of the spec (and nearly everywhere else to be honest) when I refer to driver I refer to the spark driver process, rather than the neo4j driver library. 

There are a couple of ways to fully _materialise_ an `RDD`s data in the memory of your spark driver. Kudos if you can choose the most efficient and explain your choice :smile: (hint: efficient in terms of driver process memory use). 

------------------------

### Spark drivers vs executors for the curious

The majority of code you write in any spark job is interpreted/executed on the driver process (or driver machine in a clustered environment). The exceptions to this rule are (as far you need be concerned) limited to `RDD`s. 

Though a reference to an `RDD` will exist in the memory of your spark driver process, its contents will be split across several partitions which reside in the memory of your executor processes. The only parts of your code which will be executed on executors are those parts which you write in lambdas and pass to `RDD`s (via `.map()`, `.filter()` and friends).

**Comment by sshephard2** [comment]
Thanks Hugo
